### ISSUE TITLE
Data consistency

### ISSUE THREAD

**Issue by mmhh1910** [airswap/geth-cloudformation#1]
Thanks Adam for your devcon talk and for open sourcing this!

The load balancer will simply direct to a node randomly or by round-robin, correct? Regarding consistency, is there anything preventing that a client fetches the highest block from node A and then fails to retrieve e.g. the transactions in this block since the second request ends up on node B which does not know about this block yet? Another example would be fetching pending transaction IDs and then fetching details for one of these transactions that might again not be available on another node.

**Comment by rhyeal** [comment]
That is certainly something that could happen and something that solution does not yet address. I've talked with a few other developers regarding ways to solve this problem, since it is a critical one for long-term scalability of any private geth cluster solution.

Some options that have been tossed around are:
- Re-write geth to use a common data store in Redis (and an external Redis cluster)
- Automatically add peers inside the Target Group to the health checks
- Write a middleware layer that would query every node and return back the highest block

I want to tackle another issue w/ this repo first (faster initial syncing and backups) before tackling data consistency. But if you've got an idea for this, I'm happy to review the PR!

**Comment by rhyeal** [comment]
I'm going to close this out since we are no longer maintaining this repo.
